SELECT * FROM EMPLEADOS;

SELECT * FROM EMPLEADOS;

SELECT  COUNT(*)
FROM EMPLEADOS;

SELECT * FROM EMPLEADOS;

SELECT COUNT(*)
FROM EMPLEADOS;

--DEPARTAMENTO CON MAYOR Y MENOR SUELDO
SELECT DEPARTAMENTO, SALARIO_ANUAL
FROM EMPLEADOS
ORDER BY SALARIO_ANUAL;

SELECT MIN (SALARIO_ANUAL)
FROM EMPLEADOS;

SELECT MAX (SALARIO_ANUAL)
FROM EMPLEADOS;

--IT ES EL AREA CON MENOR SUELDO CON EL SUELDO DE $40,063 Y SALES ES EL 
--DEPARTAMENTO CON MAYOR SUELDO DE $258,498

--ETNIAS CON MAYOR Y MENOR SALARIO ANUAL
SELECT ETNIA, SALARIO_ANUAL
FROM EMPLEADOS
ORDER BY SALARIO_ANUAL;

SELECT MIN (ETNIA)
FROM EMPLEADOS;

SELECT MAX (ETNIA)
FROM EMPLEADOS;

--UN ASIATICO ES EL EMPLEADO CON MENOR SALARIO ANUAL Y UN LATINO ES 
--EMPLEADO CON MAYOR SALARIO ANUAL


--PROMEDIO SALARIO ANUAL
SELECT ROUND (AVG (SALARIO_ANUAL),2)
FROM EMPLEADOS;

--EL SALARIO ANUAL PROMEDIO DE LOS EMPLEADOS ES DE $113,217.37


--CANTIDAD DE EMPLEADOS POR ETNIA
SELECT ETNIA, COUNT (SALARIO_ANUAL)
FROM EMPLEADOS
GROUP BY ETNIA
ORDER BY 2 DESC
LIMIT 4;

--HAY 404 EMPLEADOS ASIATICOS, 271 CAUCASICOS, 251 LATINOS Y 74 AFROAMERICANOS

--CANTIDAD DE EMPLEADOS POR PAIS
SELECT PAIS, COUNT (SALARIO_ANUAL)
FROM EMPLEADOS
GROUP BY PAIS
ORDER BY 2 DESC
LIMIT 3;

--HAY 643 EMPLEADOS EN ESTADOS UNIDOS, 218 EN CHINA Y 139 EN BRASIL


--PUESTO CON MAYOR Y MENOR SALARIO
SELECT PUESTO, SALARIO_ANUAL
FROM EMPLEADOS
ORDER BY SALARIO_ANUAL;

--UN IT COORDINATOR ES EL PUESTO CON MENOR SALARIO DE $40,063 Y EL PUESTO
--CON MAYOR SALARIO ES VICE PRESIDENT $258,498


--EDADES
SELECT MIN (EDAD)
FROM EMPLEADOS;

--EL EMPLEADO CON MENOR EDAD TIENE 25 AÑOS


SELECT MAX (EDAD)
FROM EMPLEADOS;

--EL EMPLEADO CON MAYOR EDAD TIENE 65

--NUMERO DE EMPLEADOS POR PUESTO
SELECT PUESTO, COUNT (SALARIO_ANUAL)
FROM EMPLEADOS
GROUP BY PUESTO
ORDER BY 2 DESC
LIMIT 10;

--SUMA, PROMEDIO, MINIMO Y MAXIMO DE SALARIO
SELECT SUM(SALARIO_ANUAL) AS SUMA,
ROUND(AVG(SALARIO_ANUAL),2)AS PROMEDIO,
MIN(SALARIO_ANUAL) AS MINIMO,
	MAX(SALARIO_ANUAL) AS MAXIMO
	FROM EMPLEADOS;

--PROMEDIO Y SUMA DE SUELDOS ANUALES TOTALES POR SEXO
SELECT SEXO, SUM(SALARIO_ANUAL)
FROM EMPLEADOS
GROUP BY SEXO;

SELECT SEXO, AVG(SALARIO_ANUAL)
FROM EMPLEADOS
GROUP BY SEXO;
--EL SEXO FEMENINO SUMO MAYORES INGRESOS POR SALARIOS ANUALES
--EL SEXO MASCULINO PROMEDIO MAYORES INGRESOS POR SALARIOS ANUALES




